
#ifndef TEXTRECOGNITION_APP_INTERFACE_ILAPLACEPLAYERAPP_H_
#define TEXTRECOGNITION_APP_INTERFACE_ILAPLACEPLAYERAPP_H_

class ILaplacePlayerApp
{
public:
    virtual ~ILaplacePlayerApp() {};        
};

#endif // !TEXTRECOGNITION_APP_INTERFACE_ILAPLACEPLAYERAPP_H_
